dist: trusty
sudo: required
matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      before_script:
        - cd spa
        - yarn
      cache:
        directories:
          - node_modules
      script:
        - yarn test

notifications:
  email: false
