dist: trusty
sudo: required
matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      before_script:
        - cd spa
        - yarn --frozen-lockfile --ignore-optional
      cache: npm
      script:
        - yarn typecheck
        - yarn lint
        - yarn test

notifications:
  email: false
