#!/bin/bash

readonly TEST=false

cd "$(dirname $0)"
verb="$1"
shift

git fetch --prune
readonly last_deploy_commit_hash="$(git rev-parse master)"
readonly last_develop_commit_hash="$(git rev-parse origin/develop)"
readonly is_production="$([ $TEST != true ] && echo true || echo false)"

set -e

# =====================================
#   Functions
# =====================================


smart-deploy() {
  deploy_type=$1
  shift

  printf "Now production commit hash\t=> ${last_deploy_commit_hash}\n"

  if [ $last_develop_commit_hash != $last_deploy_commit_hash ]; then
    printf "\e[33mDetect new develop commit\e[m\t=> ${last_develop_commit_hash}\n"

    if git status | grep --quiet 'working tree clean'; then
      git checkout master
      array=( `git describe --abbrev=0 --tags | tr -s '.' ' '`)
      $is_production && git merge origin/develop
      
      case "$deploy_type" in
        'all')
          smart-api-deploy $@
          smart-spa-deploy $@
          ;;
        'api')
          smart-api-deploy $@
          ;;
        'spa')
          smart-spa-deploy $@
          ;;
      esac

      $is_production && git push origin master
      prev_tag=${array[1]}
      tag=${array[0]}.${array[1]}.$((array[2]+1))
      $is_production && git tag $tag
      $is_production && git push origin $tag || echo $tag

      exit 0
    else
      printf "\e[31mExist NOT staged changes or commited some files\e[m\n"
      printf "\e[31;1mAborted!!\e[m\n"
      exit 1
    fi
  
  else
    printf 'Not found new develop commit.\n'
    printf "\e[31;1mAborted!!\e[m\n"
    exit 0
  fi
}

smart-spa-deploy() {
  cd "$(dirname $0)"
  if [ "$1" == "service-host" ]; then
    if git diff --name-only "$last_deploy_commit_hash".."$last_develop_commit_hash" | grep --quiet '^yarn.lock$'; then
      sudo docker-compose build --no-cache spa
    else
      sudo docker-compose build spa
    fi
    sudo docker-compose run --rm spa yarn build
  else
    cd "$(dirname $0)/spa"
    yarn
    yarn build
  fi
}

smart-api-deploy() {
  cd "$(dirname $0)"
  if [ "$1" == "service-host" ]; then
    sudo docker-compose -f docker-compose.production.yml build
    sudo docker-compose -f docker-compose.production.yml restart
    sudo docker-compose -f docker-compose.production.yml ps
  else
    docker-compose -f docker-compose.production.yml build
    docker-compose -f docker-compose.production.yml restart
    docker-compose -f docker-compose.production.yml ps
  fi
}

add_tags() {
  if [ $0 ]; then
    array=( `git describe --abbrev=0 --tags | tr -s '.' ' '`)
    prev_tag=${array[1]}
    tag=${array[0]}.${array[1]}.$((array[2]+1))
  else
    tag=$0
  fi
  $is_production && git tag $tag
  $is_production && git push origin $tag || echo $tag
}

test () {
  $is_production && echo 'test mode is false' || echo "test mode is true"
}

case "$verb" in
  'all' | 'api' | 'spa')
    smart-deploy $verb $@
    ;;
  
  'add_tag')
    add_tags $@
    ;;

  'test')
    test $@
    ;;

  *)
    set +x
    echo
    echo 'Subcommands'
    echo '  all    -- deploy spa and api service'
    echo '  spa    -- deploy spa (js)'
    echo '  api    -- deploy api (rails)'
    echo '  tag    -- add release tag'
    echo
    echo 'You can use NOSTAGE=1 environment variable if you do not want to stage.'
    exit 64
esac
