version: "3.4"
services:
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    env_file: .env

  app:
    build:
      context: ./api/
      target: release
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    environment:
      SOCKET: /rails/tmp/sockets/puma.sock
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
    restart: unless-stopped
    volumes:
      - ./api:/app
      - ./spa/build:/app/public
    ports:
      - "22222:3000"
    depends_on:
      - db
